import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import ReadMeForm from '@/components/readme-form/ReadMeForm'

export default function Home() {
  return (
    <>
      <Head>
        <title>Generate your own ReadMe file</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          <span className={styles.accentText}>Awesome</span> Profile{' '}
          <span className={styles.accentText}>README</span> Generator
        </h1>
        <ReadMeForm />
      </main>
    </>
  )
}
